### ISSUE TITLE
Keep getting invalid filter no matter what I try.

### ISSUE THREAD

**Issue by ingenium21** [logicmonitor/lm-sdk-python#3]
Hi Folks,

I keep following the instructions from the SDK documentation.  But they only provide the filter syntax when typing out the API URL, not when trying to call the method.  

For example:

I'm trying to get the snmp64_If- datasource by the device ID

```Python
def get_snmp64_If_datasource(id):
    """function to get the interface(64) datasource ID of the device"""
    filter = "name~interface"
    response = api_instance.get_device_datasource_list(id, filter=filter)
    return response
```

but that returns an invalid filter.  

the only filter that has worked for me was when I was trying to get devices from group and narrowed the filter down to a specific id.

```python
filter = "id:222"
response = api_instance.get_immediate_device_list_by_device_group_id(gid)
```

i've also tried things like:
```
data_source_display_name~Interface
dataSourceDisplayName~Interface
datasourcedisplayname~interface
data_source_name~snmp64
dataSourceName~snmp64
datasourcename~snmp64
and
data_source_name:snmp64_If-
dataSourceName:snmp64_If-
datasourcename:snmp64_If-
```

but nothing has come up.

Could you provide me with the correct syntax?
Thanks,

Ren

**Comment by elmobp** [comment]
Try this for a filter

```python

filter='id:"1"'
```
